POST http://localhost:8080/users HTTP/1.1
content-type: application/json

# {
#     "name":"pedro souza",
#     "email": "pedrinho@gmail.com",
#     "password":"12345"
# }

{
    "name":"Eudes",
    "email": "eudes@gmail.com",
    "password":"12345"
}

# {
#     "name":"Paula Andrade",
#     "email": "paula@gmail.com",
#     "password":"12345"
# }