POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmZDE0MmU3LTg0OGQtNDU5Ny1hMTcxLTU5M2Q2ZGRlNTliNyIsIm5hbWUiOiJBbWFuZGEgUGVyZWlyYSIsImVtYWlsIjoiYW1hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTcxMzI3Mzk1Nn0.Ed-O2KdS0KY4uN0h9DKA5qsaoIyFcFkH-MhL8IPNk0I

{
    "name":"sabado de sol",
    "description":"beber cerveja"
}