GET  http://localhost:3333/tasks/9d2c8233-2454-45f4-b154-ead205ed8e6e HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkMmM4MjMzLTI0NTQtNDVmNC1iMTU0LWVhZDIwNWVkOGU2ZSIsImVtYWlsIjoicGVkcmluaG9AZ21haWwuY29tIiwiaWF0IjoxNzEyNzE1NjQ0fQ.YLAhbnLuFe8OyUu8hBMQgSiCfbNCpVBJHYFlm0Tbw3U
