GET http://localhost:8080/tasks/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlNmJmYTRiLWRmYTktNGNkZC05OTliLWY0ODkzNDBlYjQwMSIsIm5hbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJpYXQiOjE3MTM0NTE4NDh9.8QOoZIAXT1Wmo7k0BUjIQ4JYrx6s1MxeRB6Ec5wkagA