PUT  http://localhost:8080/tasks/475b3d93-010e-4c38-9e07-6af31d092009 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlZWUzMmNkLTdiOGUtNDQ5Ny1hOTc3LWRjYWNhOTI4ZDkxOCIsIm5hbWUiOiJhbWFuZGEiLCJlbWFpbCI6ImFtYW5kYUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMTI1OTV9.-XggC6TkX-yHP96z3vv8Sfwq48iMDM1kDqLM6CNMw58

{
    "name":"passear com dog editado",
    "description": "passear com o dog editado"
}